#!/bin/sh
HISTFILE=$HOME/.local/share/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANWIDTH=999
export GOPATH=$HOME/.local/share/go
