#!/bin/sh
# common commands
alias p="pacman"
alias v="nvim"
alias s="systemctl"
alias ka="killall"
alias kys="poweroff"
alias py="python"
alias remote="ssh root@a-nord.se"
alias ls="exa -l --color=always --group-directories-first"
alias la="exa -la --color=always --group-directories-first"
alias rm="trash-put"
alias rmf="rm -rf"
alias rmsudo="sudo rm -rf"
alias fda="fd -u"

alias gc="cd ~/.config"
alias gd="cd ~/dev"
alias gC="cd ~/.new-dotfiles"
alias gD="cd ~/downloads"
alias go="cd ~/org"
alias gp="cd ~/pictures"
alias gv="cd ~/videos"
alias gm="cd ~/music"
alias gs="cd ~/.local/src"
alias gS="cd ~/.local/share"
alias gb="cd ~/.local/bin"
alias gM="cd /mnt"
alias gr="cd /"
alias eht="cd ~/dev/web/ehtkollen/"

alias rmnodemodules="fd -u -t d node_modules -x rm -rf {}"

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias mkdir="mkdir -pv"

alias ffmpeg="ffmpeg -hide_banner"
alias yta="yt-dlp -x -f bestaudio"

# easier to read disk
alias df='df -h'     # human-readable sizes
alias du='du -hd1 | sort -h'     # human-readable sizes
alias durecursive='du -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# remove need to type sudo
for cmd in pacman rc-update rc-service reboot poweroff mount umount docker docker-compose; do
	alias $cmd="sudo $cmd";
done; unset cmd
