#!/bin/sh
# common commands
alias p="pacman"
alias v="nvim"
alias s="systemctl"
alias ka="killall"
alias kys="poweroff"
alias py="python"
alias luchs="ssh luchs@a-nord.se"
alias ls="exa -l --color=always --group-directories-first"
alias la="exa -la --color=always --group-directories-first"
alias rmsudo="sudo rm -rf"
alias editaliases="$EDITOR $XDG_CONFIG_HOME/zsh/zsh-aliases"

alias gc="cd ~/.config"
alias gd="cd ~/dev"
alias gC="cd ~/.dotfiles"
alias gD="cd ~/Downloads"
alias gp="cd ~/Pictures"
alias gv="cd ~/Videos"
alias gm="cd ~/Music"
alias gn="cd ~/notes/home"
alias gw="cd ~/notes/work"
alias gs="cd ~/.local/sources"
alias gS="cd ~/.local/share"
alias gb="cd ~/.local/bin"
alias gM="cd /mnt"
alias gr="cd /"
alias eht="cd ~/dev/web/ehtkollen/"

alias rmnodemodules="fd -u -t d node_modules -x rm -rf {}"

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias mkdir="mkdir -pv"

alias ffmpeg="ffmpeg -hide_banner"
alias yta="yt-dlp -x -f bestaudio"

# easier to read disk
alias df='df -h'     # human-readable sizes
alias du='du -hd1 | sort -h'     # human-readable sizes

# remove need to type sudo
for cmd in pacman systemctl journalctl reboot poweroff mount umount docker docker-compose; do
	alias $cmd="sudo $cmd";
done; unset cmd
